#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : os-client-config
Version  : 1.31.2
Release  : 42
URL      : http://tarballs.openstack.org/os-client-config/os-client-config-1.31.2.tar.gz
Source0  : http://tarballs.openstack.org/os-client-config/os-client-config-1.31.2.tar.gz
Source99 : http://tarballs.openstack.org/os-client-config/os-client-config-1.31.2.tar.gz.asc
Summary  : OpenStack Client Configuation Library
Group    : Development/Tools
License  : Apache-2.0
Requires: os-client-config-python3
Requires: os-client-config-license
Requires: os-client-config-python
Requires: Sphinx
Requires: docutils
Requires: openstacksdk
Requires: reno
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
os-client-config
        ================

%package license
Summary: license components for the os-client-config package.
Group: Default

%description license
license components for the os-client-config package.


%package python
Summary: python components for the os-client-config package.
Group: Default
Requires: os-client-config-python3

%description python
python components for the os-client-config package.


%package python3
Summary: python3 components for the os-client-config package.
Group: Default
Requires: python3-core

%description python3
python3 components for the os-client-config package.


%prep
%setup -q -n os-client-config-1.31.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532270655
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/os-client-config
cp LICENSE %{buildroot}/usr/share/doc/os-client-config/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/os-client-config/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
