#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4F398DEAE440091C (infra-root@openstack.org)
#
Name     : os-client-config
Version  : 2.0.0
Release  : 52
URL      : http://tarballs.openstack.org/os-client-config/os-client-config-2.0.0.tar.gz
Source0  : http://tarballs.openstack.org/os-client-config/os-client-config-2.0.0.tar.gz
Source1  : http://tarballs.openstack.org/os-client-config/os-client-config-2.0.0.tar.gz.asc
Summary  : OpenStack Client Configuation Library
Group    : Development/Tools
License  : Apache-2.0
Requires: os-client-config-license = %{version}-%{release}
Requires: os-client-config-python = %{version}-%{release}
Requires: os-client-config-python3 = %{version}-%{release}
Requires: openstacksdk
BuildRequires : buildreq-distutils3
BuildRequires : openstacksdk
BuildRequires : pbr

%description
================
os-client-config
================

.. image:: https://governance.openstack.org/tc/badges/os-client-config.svg
    :target: https://governance.openstack.org/tc/reference/tags/index.html

.. warning::
  `os-client-config` has been superceded by `openstacksdk`_. While
  `os-client-config` will continue to exist, it is highly recommended that
  users transition to using `openstacksdk`_ directly.

`os-client-config` is a library for collecting client configuration for
using an OpenStack cloud in a consistent and comprehensive manner. It
will find cloud config for as few as 1 cloud and as many as you want to
put in a config file. It will read environment variables and config files,
and it also contains some vendor specific default values so that you don't
have to know extra info to use OpenStack

* If you have a config file, you will get the clouds listed in it
* If you have environment variables, you will get a cloud named `envvars`
* If you have neither, you will get a cloud named `defaults` with base defaults

Source
------

* Free software: Apache license
* Documentation: http://docs.openstack.org/os-client-config/latest
* Source: http://opendev.org/openstack/os-client-config
* Bugs: https://storyboard.openstack.org/#!/project/openstack/os-client-config
* Release Notes https://docs.openstack.org/releasenotes/os-client-config

.. _openstacksdk: http://docs.openstack.org/openstacksdk/latest

%package license
Summary: license components for the os-client-config package.
Group: Default

%description license
license components for the os-client-config package.


%package python
Summary: python components for the os-client-config package.
Group: Default
Requires: os-client-config-python3 = %{version}-%{release}

%description python
python components for the os-client-config package.


%package python3
Summary: python3 components for the os-client-config package.
Group: Default
Requires: python3-core
Provides: pypi(os-client-config)

%description python3
python3 components for the os-client-config package.


%prep
%setup -q -n os-client-config-2.0.0
cd %{_builddir}/os-client-config-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583193510
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/os-client-config
cp %{_builddir}/os-client-config-2.0.0/LICENSE %{buildroot}/usr/share/package-licenses/os-client-config/57aed0b0f74e63f6b85cce11bce29ba1710b422b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/os-client-config/57aed0b0f74e63f6b85cce11bce29ba1710b422b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
