#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB9069B1335700CDC (infra-root@openstack.org)
#
Name     : os-client-config
Version  : 1.26.0
Release  : 38
URL      : http://tarballs.openstack.org/os-client-config/os-client-config-1.26.0.tar.gz
Source0  : http://tarballs.openstack.org/os-client-config/os-client-config-1.26.0.tar.gz
Source99 : http://tarballs.openstack.org/os-client-config/os-client-config-1.26.0.tar.gz.asc
Summary  : OpenStack Client Configuation Library
Group    : Development/Tools
License  : Apache-2.0
Requires: os-client-config-python
Requires: PyYAML
Requires: appdirs
Requires: keystoneauth1
Requires: requestsexceptions
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: 0001-test.patch

%description
========================
Team and repository tags
========================
.. image:: http://governance.openstack.org/badges/os-client-config.svg
:target: http://governance.openstack.org/reference/tags/index.html

%package python
Summary: python components for the os-client-config package.
Group: Default

%description python
python components for the os-client-config package.


%prep
%setup -q -n os-client-config-1.26.0
%patch1 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489852799
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489852799
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
